<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BsGeo\Module'                        => __DIR__ . '/Module.php',
    'BsGeo\Controller\IndexController' => __DIR__ . '/src/BsGeo/Controller/IndexController.php',
    'BsGeoTest\Framework\TestCase'        => __DIR__ . '/tests/BsGeo/Framework/TestCase.php',
    'BsGeoTest\SampleTest'                => __DIR__ . '/tests/BsGeo/SampleTest.php',
);
